/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) vehicle_model_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s4[36] = {32, 1, 0, 32, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};

/* vehicle_model_constr_h_fun:(i0[3],i1[2],i2[],i3[46])->(o0[32]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=1.2500000000000000e+00;
  a2=arg[0]? arg[0][2] : 0;
  a3=cos(a2);
  a3=(a1*a3);
  a3=(a0-a3);
  a4=arg[3]? arg[3][10] : 0;
  a5=arg[3]? arg[3][12] : 0;
  a6=cos(a5);
  a6=(a1*a6);
  a6=(a4-a6);
  a7=(a3-a6);
  a7=casadi_sq(a7);
  a8=arg[0]? arg[0][1] : 0;
  a9=sin(a2);
  a9=(a1*a9);
  a9=(a8-a9);
  a10=arg[3]? arg[3][11] : 0;
  a11=sin(a5);
  a11=(a1*a11);
  a11=(a10-a11);
  a12=(a9-a11);
  a12=casadi_sq(a12);
  a7=(a7+a12);
  if (res[0]!=0) res[0][0]=a7;
  a7=cos(a5);
  a7=(a1*a7);
  a4=(a4+a7);
  a7=(a3-a4);
  a7=casadi_sq(a7);
  a5=sin(a5);
  a5=(a1*a5);
  a10=(a10+a5);
  a5=(a9-a10);
  a5=casadi_sq(a5);
  a7=(a7+a5);
  if (res[0]!=0) res[0][1]=a7;
  a7=cos(a2);
  a7=(a1*a7);
  a0=(a0+a7);
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a2=sin(a2);
  a2=(a1*a2);
  a8=(a8+a2);
  a11=(a8-a11);
  a11=casadi_sq(a11);
  a6=(a6+a11);
  if (res[0]!=0) res[0][2]=a6;
  a4=(a0-a4);
  a4=casadi_sq(a4);
  a10=(a8-a10);
  a10=casadi_sq(a10);
  a4=(a4+a10);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[3]? arg[3][14] : 0;
  a10=arg[3]? arg[3][16] : 0;
  a6=cos(a10);
  a6=(a1*a6);
  a6=(a4-a6);
  a11=(a3-a6);
  a11=casadi_sq(a11);
  a2=arg[3]? arg[3][15] : 0;
  a7=sin(a10);
  a7=(a1*a7);
  a7=(a2-a7);
  a5=(a9-a7);
  a5=casadi_sq(a5);
  a11=(a11+a5);
  if (res[0]!=0) res[0][4]=a11;
  a11=cos(a10);
  a11=(a1*a11);
  a4=(a4+a11);
  a11=(a3-a4);
  a11=casadi_sq(a11);
  a10=sin(a10);
  a10=(a1*a10);
  a2=(a2+a10);
  a10=(a9-a2);
  a10=casadi_sq(a10);
  a11=(a11+a10);
  if (res[0]!=0) res[0][5]=a11;
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a7=(a8-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  if (res[0]!=0) res[0][6]=a6;
  a4=(a0-a4);
  a4=casadi_sq(a4);
  a2=(a8-a2);
  a2=casadi_sq(a2);
  a4=(a4+a2);
  if (res[0]!=0) res[0][7]=a4;
  a4=arg[3]? arg[3][18] : 0;
  a2=arg[3]? arg[3][20] : 0;
  a6=cos(a2);
  a6=(a1*a6);
  a6=(a4-a6);
  a7=(a3-a6);
  a7=casadi_sq(a7);
  a11=arg[3]? arg[3][19] : 0;
  a10=sin(a2);
  a10=(a1*a10);
  a10=(a11-a10);
  a5=(a9-a10);
  a5=casadi_sq(a5);
  a7=(a7+a5);
  if (res[0]!=0) res[0][8]=a7;
  a7=cos(a2);
  a7=(a1*a7);
  a4=(a4+a7);
  a7=(a3-a4);
  a7=casadi_sq(a7);
  a2=sin(a2);
  a2=(a1*a2);
  a11=(a11+a2);
  a2=(a9-a11);
  a2=casadi_sq(a2);
  a7=(a7+a2);
  if (res[0]!=0) res[0][9]=a7;
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a10=(a8-a10);
  a10=casadi_sq(a10);
  a6=(a6+a10);
  if (res[0]!=0) res[0][10]=a6;
  a4=(a0-a4);
  a4=casadi_sq(a4);
  a11=(a8-a11);
  a11=casadi_sq(a11);
  a4=(a4+a11);
  if (res[0]!=0) res[0][11]=a4;
  a4=arg[3]? arg[3][22] : 0;
  a11=arg[3]? arg[3][24] : 0;
  a6=cos(a11);
  a6=(a1*a6);
  a6=(a4-a6);
  a10=(a3-a6);
  a10=casadi_sq(a10);
  a7=arg[3]? arg[3][23] : 0;
  a2=sin(a11);
  a2=(a1*a2);
  a2=(a7-a2);
  a5=(a9-a2);
  a5=casadi_sq(a5);
  a10=(a10+a5);
  if (res[0]!=0) res[0][12]=a10;
  a10=cos(a11);
  a10=(a1*a10);
  a4=(a4+a10);
  a10=(a3-a4);
  a10=casadi_sq(a10);
  a11=sin(a11);
  a11=(a1*a11);
  a7=(a7+a11);
  a11=(a9-a7);
  a11=casadi_sq(a11);
  a10=(a10+a11);
  if (res[0]!=0) res[0][13]=a10;
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a2=(a8-a2);
  a2=casadi_sq(a2);
  a6=(a6+a2);
  if (res[0]!=0) res[0][14]=a6;
  a4=(a0-a4);
  a4=casadi_sq(a4);
  a7=(a8-a7);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  if (res[0]!=0) res[0][15]=a4;
  a4=arg[3]? arg[3][26] : 0;
  a7=arg[3]? arg[3][28] : 0;
  a6=cos(a7);
  a6=(a1*a6);
  a6=(a4-a6);
  a2=(a3-a6);
  a2=casadi_sq(a2);
  a10=arg[3]? arg[3][27] : 0;
  a11=sin(a7);
  a11=(a1*a11);
  a11=(a10-a11);
  a5=(a9-a11);
  a5=casadi_sq(a5);
  a2=(a2+a5);
  if (res[0]!=0) res[0][16]=a2;
  a2=cos(a7);
  a2=(a1*a2);
  a4=(a4+a2);
  a2=(a3-a4);
  a2=casadi_sq(a2);
  a7=sin(a7);
  a7=(a1*a7);
  a10=(a10+a7);
  a7=(a9-a10);
  a7=casadi_sq(a7);
  a2=(a2+a7);
  if (res[0]!=0) res[0][17]=a2;
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a11=(a8-a11);
  a11=casadi_sq(a11);
  a6=(a6+a11);
  if (res[0]!=0) res[0][18]=a6;
  a4=(a0-a4);
  a4=casadi_sq(a4);
  a10=(a8-a10);
  a10=casadi_sq(a10);
  a4=(a4+a10);
  if (res[0]!=0) res[0][19]=a4;
  a4=arg[3]? arg[3][30] : 0;
  a10=arg[3]? arg[3][32] : 0;
  a6=cos(a10);
  a6=(a1*a6);
  a6=(a4-a6);
  a11=(a3-a6);
  a11=casadi_sq(a11);
  a2=arg[3]? arg[3][31] : 0;
  a7=sin(a10);
  a7=(a1*a7);
  a7=(a2-a7);
  a5=(a9-a7);
  a5=casadi_sq(a5);
  a11=(a11+a5);
  if (res[0]!=0) res[0][20]=a11;
  a11=cos(a10);
  a11=(a1*a11);
  a4=(a4+a11);
  a11=(a3-a4);
  a11=casadi_sq(a11);
  a10=sin(a10);
  a10=(a1*a10);
  a2=(a2+a10);
  a10=(a9-a2);
  a10=casadi_sq(a10);
  a11=(a11+a10);
  if (res[0]!=0) res[0][21]=a11;
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a7=(a8-a7);
  a7=casadi_sq(a7);
  a6=(a6+a7);
  if (res[0]!=0) res[0][22]=a6;
  a4=(a0-a4);
  a4=casadi_sq(a4);
  a2=(a8-a2);
  a2=casadi_sq(a2);
  a4=(a4+a2);
  if (res[0]!=0) res[0][23]=a4;
  a4=arg[3]? arg[3][34] : 0;
  a2=arg[3]? arg[3][36] : 0;
  a6=cos(a2);
  a6=(a1*a6);
  a6=(a4-a6);
  a7=(a3-a6);
  a7=casadi_sq(a7);
  a11=arg[3]? arg[3][35] : 0;
  a10=sin(a2);
  a10=(a1*a10);
  a10=(a11-a10);
  a5=(a9-a10);
  a5=casadi_sq(a5);
  a7=(a7+a5);
  if (res[0]!=0) res[0][24]=a7;
  a7=cos(a2);
  a7=(a1*a7);
  a4=(a4+a7);
  a7=(a3-a4);
  a7=casadi_sq(a7);
  a2=sin(a2);
  a2=(a1*a2);
  a11=(a11+a2);
  a2=(a9-a11);
  a2=casadi_sq(a2);
  a7=(a7+a2);
  if (res[0]!=0) res[0][25]=a7;
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a10=(a8-a10);
  a10=casadi_sq(a10);
  a6=(a6+a10);
  if (res[0]!=0) res[0][26]=a6;
  a4=(a0-a4);
  a4=casadi_sq(a4);
  a11=(a8-a11);
  a11=casadi_sq(a11);
  a4=(a4+a11);
  if (res[0]!=0) res[0][27]=a4;
  a4=arg[3]? arg[3][38] : 0;
  a11=arg[3]? arg[3][40] : 0;
  a6=cos(a11);
  a6=(a1*a6);
  a6=(a4-a6);
  a10=(a3-a6);
  a10=casadi_sq(a10);
  a7=arg[3]? arg[3][39] : 0;
  a2=sin(a11);
  a2=(a1*a2);
  a2=(a7-a2);
  a5=(a9-a2);
  a5=casadi_sq(a5);
  a10=(a10+a5);
  if (res[0]!=0) res[0][28]=a10;
  a10=cos(a11);
  a10=(a1*a10);
  a4=(a4+a10);
  a3=(a3-a4);
  a3=casadi_sq(a3);
  a11=sin(a11);
  a1=(a1*a11);
  a7=(a7+a1);
  a9=(a9-a7);
  a9=casadi_sq(a9);
  a3=(a3+a9);
  if (res[0]!=0) res[0][29]=a3;
  a6=(a0-a6);
  a6=casadi_sq(a6);
  a2=(a8-a2);
  a2=casadi_sq(a2);
  a6=(a6+a2);
  if (res[0]!=0) res[0][30]=a6;
  a0=(a0-a4);
  a0=casadi_sq(a0);
  a8=(a8-a7);
  a8=casadi_sq(a8);
  a0=(a0+a8);
  if (res[0]!=0) res[0][31]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int vehicle_model_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int vehicle_model_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int vehicle_model_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void vehicle_model_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int vehicle_model_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void vehicle_model_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void vehicle_model_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void vehicle_model_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int vehicle_model_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int vehicle_model_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real vehicle_model_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vehicle_model_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vehicle_model_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* vehicle_model_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* vehicle_model_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int vehicle_model_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
